services:
  app:
    environment:
      - LOG_LEVEL=DEBUG
      - DATASOURCE_HOST_PORT=postgres:5432
      - DATASOURCE_USERNAME=postgres
      - DATASOURCE_PASSWORD=postgres
      - DATASOURCE_DBNAME=crime_assessment_service
      - SENTRY_ENV=development
      - SENTRY_SAMPLE_RATE=0.0
    env_file:
      - app.env
    ports:
      - "8081:8081"
    entrypoint: java
    command:
      - "-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:8081"
      - "-jar"
      - "app.jar"
        
  postgres:
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=crime_assessment_service