name: CI

jobs:
  commit_lint:
    runs-on: ubuntu-latest
    on:
      pull_request:
        types: [ push, pull_request ]
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Install commitlint
        run: npm install -D @commitlint/cli @commitlint/config-conventional
      - name: Validate all PR commits
        run: npx commitlint --from ${{ github.event.pull_request.base.sha }} --to ${{ github.event.pull_request.head.sha }} --verbose

  pr_checks:
    runs-on: ubuntu-latest
    on:
      pull_request:
        types: [opened, reopened, edited, ready_for_review]
    steps:
      - name: PR description check
        env:
          DESCRIPTION: ${{ github.event.pull_request.body }}
        run: |
          if [[ $DESCRIPTION == *"Describe what you did and why"* ]]; then
            echo "Please add a meaningful description to your PR."
            exit 1
          fi
      - name: PR commit count check
        env:
          COMMIT_COUNT: ${{ github.event.pull_request.commits }}
        run: |
          commit_limit=40

          if (( $COMMIT_COUNT > $commit_limit )); then
            echo "You have exceeded the recommended limit of $commit_limit commits in this PR. Please fix-up your commits to make them more individually meaningful."
            exit 1
          fi
      - name: Jira link check
        env:
          DESCRIPTION: ${{ github.event.pull_request.body }}
        run: |
          if [[ $DESCRIPTION =~ https://dsdmoj.atlassian.net/browse/[A-Za-z]+-[xX]+ ]]; then
            echo "Please update the Jira link to point to the corresponding work item(s)."
            exit 1
          fi
